version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  simpleapi:
    image: annesne/simpleapi:arbk
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=testdb;User=root;Password=your_password;
    ports:
      - "8080:80"

  nginx:
    image: annesne/nginx:arbk
    ports:
      - "80:80"
    depends_on:
      - simpleapi